baseURL: "https://alessandrosellitto.github.io/"
title: "Alessandro Sellitto - Economics PhD Candidate"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
      weight: 2

params:
  description: "PhD Candidate in Economics. Research in AI Economics, Digital Economics, Empirical IO, and Behavioral Economics."
  keywords: ["Alessandro Sellitto", "Economics", "AI Economics", "Digital Economics", "Empirical IO"]
  author: "Alessandro Sellitto"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: "Alessandro Sellitto"
    subtitle: "I am a PhD Candidate in Economics at the University of Milan and the University of Pavia, and Research Affiliate at the Düsseldorf Institute for Competition Economics (DICE). I have been a visiting researcher at DICE (October 2024–March 2025), the European Commission’s Joint Research Centre (April 2025–August 2025), and the Toulouse School of Economics (January 2026). My research focuses on the economics of AI, digital economics, empirical IO, and behavioral economics."
    imageUrl: "picture.jpeg"
    imageWidth: 160
    imageHeight: 0
    buttons:
      - name: Research
        url: research/

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: "mailto:alessandro.sellitto@unimi.it"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/alessandrosellitto"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=L6EWq5IAAAAJ&hl=it"
    - name: ORCID
      url: "https://orcid.org/0009-0004-9534-2886"

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Alessandro Sellitto"
    icon: "favicon.ico"
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    style: autumn

  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
